import { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";

export default function Home() {
  useEffect(() => {
    axios.post("/api/twilio/send-message", {
      phone: "+17047713395",
      message: "Hello aidan, This is muneeb!",
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello world</main>
    </>
  );
}
